add_newline = true

format = """
$character $git_metrics $git_state $git_status
$username $directory $git_branch $cmd_duration\
$python\
$c\
$php\
$nodejs\
$cmake\
$java\
$haskell
 [{}](bold white) """

right_format = "$git_commit $time"


[username]
show_always = true
style_root = "fg: green"
style_user = "fg:#f9f1a5 bg:#212227"
format = "[î‚¶](fg:#212227)[$user]($style)[î‚°](fg:#212227)"


[cmd_duration]
min_time = 1000

[character]
success_symbol = " ğŸ”¥ "
error_symbol = "[-ğŸ‘](bold red)"

[directory]
style = "fg:#EFC88B"
format = "[ï“ $path]($style)"
repo_root_format = "[ï‡’ $repo_root]($repo_root_style)[$path]($style)"
repo_root_style = "fg:#5EFC8D"
truncation_length = 3 
truncate_to_repo = true
truncation_symbol = "â€¦"


[git_commit]
format = "[DETACHED head](bold red): [$hash]($style)"

[git_status]
# conflicted = "âš”ï¸ "
# ahead = "â‡¡${count}"
# behind = "â‡£${count}"
# diverged = "ğŸ”±(â‡¡${ahead_count} â‡£${behind_count})"
# untracked = "_Ã—${count}"
# stashed = "ğŸ“¦"
# modified = "ğŸ“${count} "
# staged = "ğŸ—ƒï¸Ã—${count} "
# renamed = "ï¥” Ã—${count}"
# deleted = "ğŸ—‘ï¸Ã—${count}"
# style = "bright-white"
format = "$all_status$ahead_behind"

[time]
disabled = false
time_format = "%H:%M"

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "


[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "
